version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      allow:
          - dependency-name: "@apst/biome"
          - dependency-name: "@apst/tsconfig"
          - dependency-name: "@biomejs/biome"
          - dependency-name: "npm-run-all2"
          - dependency-name: "tsup"
          - dependency-name: "typedoc"
          - dependency-name: "typedoc-plugin-markdown"
          - dependency-name: "typescript"
          - dependency-name: "vite"
          - dependency-name: "vitest"
